site_name: How to connect a Zune device to the Zune software
site_url: https://josh-wong.github.io/zune-software-setup/
site_description: A tutorial that describes how to connect a Microsoft Zune device to the Zune software.

# Add repo details in the top right-hand corner
repo_name: josh-wong/zune-software-setup
repo_url: https://github.com/josh-wong/zune-software-setup/
edit_uri: blob/main/docs

plugins:
  - search
  # Enables TechDocs support in Backstage. However, many plugins need to be disabled for TechDocs to work properly.
  #- techdocs-core
  # Show the last updated date
  - git-revision-date-localized:
      type: date
  # Enable videos to be embedded
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  - git-committers:
      repository: josh-wong/zune-software-setup
      branch: main
  - rss:
      abstract_chars_count: 160  # -1 for full content
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

markdown_extensions:
  # Add styles for buttons
#  - attr_list
  # Add emoji support
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add support for Material for MkDocs admonitions
#  - admonition
#  - pymdownx.details
#  - pymdownx.superfences
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: mkdocs
#  name: material
  # Add favicon to browser tab
  favicon: assets/images/favicon.png
  # Add logo to docs pages
  logo: assets/images/mkdocs_zune_logo.png
  icon:
    # Add icon to show repository information and link
#    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
#    admonition:
#      note: fontawesome/solid/note-sticky
#      abstract: fontawesome/solid/book
#      info: fontawesome/solid/circle-info
#      tip: fontawesome/solid/bullhorn
#      success: fontawesome/solid/check
#      question: fontawesome/solid/circle-question
#      warning: fontawesome/solid/triangle-exclamation
#      failure: fontawesome/solid/bomb
#      danger: fontawesome/solid/skull
#      bug: fontawesome/solid/robot
#      example: fontawesome/solid/flask
#      quote: fontawesome/solid/quote-left
  # Add light & dark theme
#  palette:
    # Palette toggle for automatic mode
#    - media: "(prefers-color-scheme)"
#      toggle:
#        icon: material/brightness-auto
#        name: Switch to light mode
    # Palette toggle for light mode
#    - media: "(prefers-color-scheme: light)" 
#      scheme: default
#      toggle:
#        icon: material/weather-night
#        name: Switch to dark mode
#      primary: pink
#      accent: blue
    # Palette toggle for dark mode
#    - media: "(prefers-color-scheme: dark)" 
#      scheme: slate
#      toggle:
#        icon: material/weather-sunny
#        name: Switch to light mode
#      primary: pink
#      accent: blue
#  features:
    # Add custom search functions
#    - search.suggest
#    - search.highlight
#    - search.share
#    - navigation.tracking
#    - navigation.top

#extra:
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/josh-wong
#      name: josh-wong on GitHub
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/in/wongjoshua
#      name: Joshua Wong on LinkedIn
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/josh_in_japan
#      name: josh_in_japan on Twitter

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Installing the Zune software: '02_installing-the-zune-software.md'
  - Connecting to the Zune software: '03_connecting-with-the-zune-software.md'
  - Adding apps and games (Zune HD only): '04_adding-apps-and-games.md'
  - Conclusion: '05_conclusion.md'
  - References: '06_references.md'
  - Contributions: '07_contributions.md'
  - '': ''
  - üî∂RSS: 'https://josh-wong.github.io/zune-software-setup/feed_rss_updated.xml'
  - '': ''
  - '': ''
  - üè†Home: 'https://josh-wong.github.io'